### ISSUE TITLE
KeyError on session_id

### ISSUE THREAD

**Issue by ShadwDrgn** [tony/libtmux#36]
I created a tmux session called 'minecraft' and a window named 'server' manually. also there's a 'bash' window. anything i do to search panes or show _panes or list_panes() or attached_pane gives the same error:

```python
>>> import libtmux
>>>
>>> tmux = libtmux.Server()
>>> ses = tmux.find_where({'session_name': 'minecraft'})
>>> win = ses.find_where({'window_name': 'server'})
>>> win
Window(@1 1:server, Session($0 minecraft))
>>> win.attached_pane
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/libtmux/window.py", line 441, in attached_pane
    for pane in self._panes:
  File "/usr/local/lib/python2.7/dist-packages/libtmux/window.py", line 466, in _panes
    return self._list_panes()
  File "/usr/local/lib/python2.7/dist-packages/libtmux/window.py", line 455, in _list_panes
    p for p in panes if p['session_id'] == self.get('session_id')
KeyError: u'session_id'
>>>
```

**Comment by tony** [comment]
```
>>> tmux.find_where({'session_name': 'libtmux'}).find_where({'window_name': 'libtmux'}).attached_pane
Pane(%10 Window(@4 1:libtmux, Session($1 libtmux)))
```

I can't reproduce this.   Is the parent session (mineraft) changing?

Can you let me know your platform, python, libtmux and tmux version?

**Comment by ShadwDrgn** [comment]
tmux 2.1
python 2.7.12
libtmux==0.6.5
Ubuntu 16.04

user@host:~/$ tmux list-panes -a
minecraft:0.0: [200x43] [history 1857/2000, 2089756 bytes] %0 (active)
minecraft:1.0: [200x43] [history 1348/2000, 1623574 bytes] %1 (active)
minecraft:2.0: [200x43] [history 377/2000, 371726 bytes] %2 (active)

**Comment by tony** [comment]
So the behavior is still happening, after you tried it again?

Can you give me your `tmux list-sessions` and `tmux list-windows -a`?

**Comment by ShadwDrgn** [comment]
$ tmux list-sessions
minecraft: 3 windows (created Mon Apr 17 23:09:41 2017) [200x43]

$ tmux list-windows -a
minecraft:0: python- (1 panes) [200x43]
minecraft:1: server (1 panes) [200x43]
minecraft:2: bash* (1 panes) [200x43]

**Comment by MaienM** [comment]
I also ran into this issue, and I've managed to track down the cause/a reproduction scenario.

I started a new tmux server instance, and from the first window, I launched a new-window with a command with a newline in it: `tmux new-window -t :2 -k $'echo foo\nread'`. I then switched back to the first window, and ran the following in Python:

```
>>> import libtmux
>>> libtmux.__version__
'0.8.2'
>>> tmux = libtmux.Server()
>>> tmux.find_where({'session_name': '0'}).find_where({'window_name': 'python'}).attached_pane
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maienm/.asdf/installs/python/utils/lib/python3.8/site-packages/libtmux/window.py", line 490, in attached_pane
    for pane in self._panes:
  File "/home/maienm/.asdf/installs/python/utils/lib/python3.8/site-packages/libtmux/window.py", line 514, in _panes
    return self._list_panes()
  File "/home/maienm/.asdf/installs/python/utils/lib/python3.8/site-packages/libtmux/window.py", line 506, in _list_panes
    panes = [p for p in panes if p['session_id'] == self.get('session_id')]
  File "/home/maienm/.asdf/installs/python/utils/lib/python3.8/site-packages/libtmux/window.py", line 506, in <listcomp>
    panes = [p for p in panes if p['session_id'] == self.get('session_id')]
KeyError: 'session_id'
>>> tmux._update_panes()._panes
[{'session_name': '0', 'session_id': '$0', 'window_index': '1', 'window_id': '@0', 'window_name': 'python', 'history_size': '137', 'history_limit': '100000', 'history_bytes': '100636', 'pane_index': '1', 'pane_width': '240', 'pane_height': '66', 'pane_title': 'HOSTNAME', 'pane_id': '%0', 'pane_active': '1', 'pane_dead': '0', 'pane_in_mode': '0', 'pane_synchronized': '0', 'pane_tty': '/dev/pts/41', 'pane_pid': '337481', 'pane_current_path': '/home/maienm', 'pane_current_command': 'python', 'cursor_x': '0', 'cursor_y': '65', 'scroll_region_upper': '0', 'scroll_region_lower': '65', 'alternate_on': '0', 'alternate_saved_x': '0', 'alternate_saved_y': '0', 'cursor_flag': '1', 'insert_flag': '0', 'keypad_cursor_flag': '0', 'keypad_flag': '0', 'wrap_flag': '1', 'mouse_standard_flag': '0', 'mouse_button_flag': '0', 'mouse_any_flag': '0'}, {'session_name': '0', 'session_id': '$0', 'window_index': '2', 'window_id': '@2', 'window_name': 'zsh', 'history_size': '0', 'history_limit': '100000', 'history_bytes': '0', 'pane_index': '1', 'pane_width': '240', 'pane_height': '66', 'pane_title': 'HOSTNAME', 'pane_id': '%2', 'pane_active': '1', 'pane_dead': '0', 'pane_in_mode': '0', 'pane_synchronized': '0', 'pane_tty': '/dev/pts/42', 'pane_pid': '338918', 'pane_start_command': 'echo foo'}, {'session_name': 'read', 'window_index': '/home/maienm', 'window_id': 'zsh', 'window_name': '0', 'history_size': '1', 'history_limit': '0', 'history_bytes': '65', 'pane_height': '0', 'pane_title': '0', 'pane_id': '0', 'pane_active': '1', 'pane_dead': '0', 'pane_in_mode': '0', 'pane_synchronized': '0', 'pane_tty': '1', 'pane_pid': '0', 'pane_start_command': '0', 'pane_start_path': '0', 'pane_current_path': ''}]
```

It looks like the newline in `pane_start_command` causes the information for the second window to be broken into two dictionaries, each with part of the information.
